In [3]:
import pandas as pd

In [4]:
bridge_data = pd.read_csv('../data/NY23BridgeInspectionData - For Analysis.csv')

bridge_data.head()

/var/folders/75/4nzp2myd4fb4xmcrl1k19g7w0000gn/T/ipykernel_17591/2493949755.py:1: DtypeWarning: Columns (7,36,38,39,71,73,96,98,102,107,108) have mixed types. Specify dtype option on import or set low_memory=False.
  bridge_data = pd.read_csv('../data/NY23BridgeInspectionData - For Analysis.csv')

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,36.0,1000040,1.0,2.0,1.0,1,0.0,87.0,119.0,44831.0,...,Y,5,15831.0,2041.0,NaN,N,36.0,F,5.0,428.13
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36.0,1000090,1.0,2.0,1.0,1,0.0,87.0,119.0,64309.0,...,Y,N,23814.0,2041.0,NaN,N,36.0,F,5.0,1522.56
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
bridge_data.columns

Index(['STATE_CODE_001', 'STRUCTURE_NUMBER_008', 'RECORD_TYPE_005A',
       'ROUTE_PREFIX_005B', 'SERVICE_LEVEL_005C', 'ROUTE_NUMBER_005D',
       'DIRECTION_005E', 'HIGHWAY_DISTRICT_002', 'COUNTY_CODE_003',
       'PLACE_CODE_004',
       ...
       'BRIDGE_LEN_IND_112', 'SCOUR_CRITICAL_113', 'FUTURE_ADT_114',
       'YEAR_OF_FUTURE_ADT_115', 'MIN_NAV_CLR_MT_116', 'FED_AGENCY',
       'SUBMITTED_BY', 'BRIDGE_CONDITION', 'LOWEST_RATING', 'DECK_AREA'],
      dtype='object', length=123)

In [21]:
bridge_data.sort_values(by="COUNTY_CODE_003")

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1081,36.0,1007570,1.0,2.0,1.0,0009W,0.0,11.0,1.0,6354.0,...,Y,N,7351.0,2041.0,NaN,N,36.0,P,4.0,1653.26
1083,36.0,1007580,1.0,2.0,1.0,0009W,0.0,11.0,1.0,6354.0,...,Y,8,8984.0,2041.0,NaN,N,36.0,F,6.0,533.18
1085,36.0,1007590,1.0,3.0,1.0,32,0.0,11.0,1.0,6354.0,...,Y,N,12384.0,2041.0,NaN,N,36.0,F,6.0,608.94
1087,36.0,1007610,1.0,2.0,1.0,0009W,0.0,11.0,1.0,1000.0,...,Y,8,28130.0,2041.0,NaN,N,36.0,F,6.0,3127.68
2469,36.0,1015980,1.0,2.0,1.0,20,0.0,11.0,1.0,1000.0,...,Y,N,19802.0,2041.0,NaN,N,36.0,F,5.0,1294.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
statenisl_bridges = bridge_data[bridge_data["COUNTY_CODE_003"] == 85].sort_values(by="COUNTY_CODE_003")
statenisl_bridges.head()

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
34607,36.0,5523051,1.0,1.0,1.0,278,0.0,N5,85.0,51000.0,...,Y,5,38697.0,2039.0,NaN,N,36.0,G,9.0,13007.50
34609,36.0,5523052,1.0,1.0,1.0,278,0.0,N5,85.0,51000.0,...,Y,5,43598.0,2041.0,NaN,N,36.0,G,9.0,10350.63
34611,36.0,00000000552305A,1.0,1.0,1.0,278,0.0,N5,85.0,51000.0,...,Y,8,87195.0,2041.0,NaN,N,36.0,G,9.0,17481.16
34613,36.0,00000000552305B,1.0,1.0,1.0,278,0.0,N5,85.0,51000.0,...,Y,8,89467.0,2036.0,NaN,N,36.0,G,9.0,14536.71
34615,36.0,00000000552305C,1.0,1.0,1.0,278,0.0,N5,85.0,51000.0,...,Y,N,87195.0,2041.0,NaN,N,36.0,G,9.0,7854.03

In [13]:
bad_bridges = statenisl_bridges[statenisl_bridges["LOWEST_RATING"] <= 6].sort_values(by="LOWEST_RATING")
bad_bridges.head()

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
18499,36.0,2249820,1.0,5.0,0.0,0,0.0,N5,85.0,51000.0,...,Y,4,15548.0,2041.0,NaN,N,36.0,P,4.0,146.02
10719,36.0,1067730,1.0,5.0,0.0,0,0.0,N5,85.0,51000.0,...,Y,N,8630.0,2041.0,NaN,N,36.0,P,4.0,974.55
10655,36.0,1067520,1.0,5.0,0.0,0,0.0,N5,85.0,51000.0,...,Y,N,11702.0,2041.0,NaN,N,36.0,P,4.0,1108.31
10657,36.0,1067530,1.0,5.0,0.0,0,0.0,N5,85.0,51000.0,...,Y,N,7814.0,2041.0,NaN,N,36.0,P,4.0,1244.34
34619,36.0,5523069,1.0,2.0,1.0,440,0.0,N5,85.0,51000.0,...,Y,5,101017.0,2041.0,NaN,N,36.0,F,5.0,12161.90